name: x86-windows

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main", "dev" ]

env:
  BUILD_TYPE: release
  PACKAGE_DIR: windows_virtual_environment_x64

jobs:
  skip_check:
    continue-on-error: false
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        paths_ignore: '["**/README.md", "**/docs/**", "**/LICENSE.txt"]'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Strict Lint
      shell: bash
      run: cargo clippy --profile ${{env.BUILD_TYPE}} -- -D warnings

    - name: Build
      shell: bash
      run: cargo build --profile ${{env.BUILD_TYPE}}

    - name: Run
      shell: bash
      run: |
        export DIR=./target/${{env.BUILD_TYPE}}/
        $DIR/start_environment.exe $DIR/print_environment.exe
        $DIR/start_environment.exe $DIR/print_registry.exe

    - name: Copy files
      shell: bash
      run: |
        mkdir -p ${{env.PACKAGE_DIR}}
        cp ./target/${{env.BUILD_TYPE}}/*.exe ${{env.PACKAGE_DIR}}/
        cp ./README.md ${{env.PACKAGE_DIR}}/
        cp ./environment_config.json ${{env.PACKAGE_DIR}}/

    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.PACKAGE_DIR}}
        path: ${{github.workspace}}/${{env.PACKAGE_DIR}}
